// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RozkladNpuAspNetCore.Utils;

namespace RozkladNpuAspNetCore.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20181225134207_AddQueryCounterToRozkladUser")]
    partial class AddQueryCounterToRozkladUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("RozkladNpuAspNetCore.Models.RozkladUser", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ExternalGroupId");

                    b.Property<string>("FacultyShortName");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("LastAction");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<int>("QueryCount");

                    b.Property<int>("TelegramId");

                    b.HasKey("Guid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
