version: "3.7"
services:
  rozklad-app:
    image: matryoshka/rozklad-app:dev
    env_file: 
      - ./env-files/rozklad-app.env
    volumes:
      - "/f/Docs/Projects/Sharp/RozkladNpuBot/RozkladNpuBot.WebApi/Properties/:/secrets/"

  mysql_db:
    env_file: 
      - ./env-files/mysql-db.env
    
  mongo:
    env_file:
    - ./env-files/mongo.env
    
  web:
    image: matryoshka/rozklad-nginx:dev
    volumes:
      - "/f/Docs/Projects/Sharp/RozkladNpuBot/docker-build/nginx/nginx-certs/Development/:/certs/"