version: "3.7"
services:
  rozklad-app:
    image: matryoshka/rozklad-app:dev
    environment: 
      ASPNETCORE_ENVIRONMENT: DockerDevel
    volumes:
      - "rozklad-app-dev-secrets:/secrets/"

  mysql_db:
    env_file: 
      - ./env-files/mysql-db.env
    
  mongo:
    env_file:
    - ./env-files/mongo.env
    
  web:
    image: matryoshka/rozklad-nginx:dev
    volumes:
      - "rozklad-nginx-dev-certs:/certs/"
      
volumes:
  rozklad-app-dev-secrets:
    external: true
  rozklad-nginx-dev-certs:
    external: true