// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NpuRozklad.Persistence;

namespace NpuRozklad.Persistence.EfMigrations
{
    [DbContext(typeof(NpuRozkladContext))]
    partial class NpuRozkladContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NpuRozklad.Persistence.RozkladUserWrapper", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("FacultyGroupsTypeIds")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Guid");

                    b.ToTable("RozkladUserWrappers");
                });
#pragma warning restore 612, 618
        }
    }
}
